### ISSUE TITLE
Support for django 4.1 and 4.2

### ISSUE THREAD

**Issue by aqeelat** [hassaanalansary/django-bulk-tracker#6]
Hi @hassaanalansary 
Can you please confirm support for django 4.1 and 4.2?

**Comment by hassaanalansary** [comment]
Yes both are supported

this is the matrix of the supported platforms
    py{39,310,311}-dj{32,40,41}
    py{310,311}-dj{42,main}
    
you can find it `tox.ini`

**Comment by aqeelat** [comment]
It would be helpful if you can add it to the trove classifiers.Sent from my iPhoneOn Jul 23, 2023, at 7:20 PM, hassaanalansary ***@***.***> wrote:﻿
Yes both are supported
this is the matrix of the supported platforms
py{39,310,311}-dj{32,40,41}
py{310,311}-dj{42,main}
you can find it tox.ini

**Comment by hassaanalansary** [comment]
I will try
